export const SET_TOGGLE = "SET_TOGGLE"
export const SET_TOGGLE_2 = "SET_TOGGLE_2"
export const SET_TRANSLATE = "SET_TRANSLATE"

export const SET_MEDIA_SPONSOR_EFFECT = "SET_MEDIA_SPONSOR_EFFECT"

export const SET_GUEST_SPEAKER_EFFECT = "SET_GUEST_SPEAKER_EFFECT"