export const SET_HEADER_EFFECT = "SET_HEADER_EFFECT"

export const SET_MEDIA_SPONSOR_EFFECT = "SET_MEDIA_SPONSOR_EFFECT"

export const SET_GUEST_SPEAKER_EFFECT = "SET_GUEST_SPEAKER_EFFECT"

export const SET_BACK_TO_HOME = "SET_BACK_TO_HOME"